---
- hosts: localhost
  connection: local
  vars:
    aws_config_dir: "{{ansible_env.HOME}}/.aws"
    bash_profile: "{{ansible_env.HOME}}/.bash_profile"
    bashrc: "{{ansible_env.HOME}}/.bashrc"
  tasks:
    ###
    # gem
    ###
    - name: updates gem packages
      gem:
        name: "{{item}}"
        state: latest
      with_items:
      - bundler
      - rubocop
      - travis
      - travis-lint
      tags:
      - skip_ansible_lint
    ###
    # git
    ###
    - name: adds global .gitignore
      file:
        src: "{{playbook_dir}}/files/gitignore"
        dest: "{{ansible_env.HOME}}/.gitignore"
        state: link
    - name: adds block into .gitconfig
      blockinfile:
        path: "{{ansible_env.HOME}}/.gitconfig"
        state: present
        content: |
          [core]
              editor = /usr/bin/vim
              excludesfile = /Users/jylitalo/.gitignore
          [push]
              default = simple
    ###
    # gnupg
    ###
    - name: gpg.conf file should exist
      file:
        path: "{{ansible_env.HOME}}/.gnupg/gpg.conf"
        state: touch
    - name: uncomment chartset from gpg config
      lineinfile:
        dest: "{{ansible_env.HOME}}/.gnupg/gpg.conf"
        regexp: '^#.*charset utf-8$'
        line: 'charset utf-8'
