set expandtab
set laststatus=2
set number
set statusline+=%F\ %l\:%c
set shiftwidth=2
syntax on
let g:terraform_align=1
execute pathogen#infect()
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
